name: bellboy_customer
description: A new Flutter project for bellboy customer application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #FOR UI
  sizer: ^2.0.15


  #FOR STATE MANAGEMENT
  flutter_bloc: ^8.1.3

  #FOR UTIL
  logger:
  flutter_svg: ^1.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost_bold.ttf
          weight: 700
        - asset: assets/fonts/jost_medium.ttf
          weight: 500
        - asset: assets/fonts/jost_regular.ttf
          weight: 400